### ISSUE TITLE
Edit box does not close after a second edit is made

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord-box3/checking-tool-rcl#18]
Edit box in the expanded scripture pane does  not close after one edit is made and saved. The edits are not lost but it is confusing to the user as if the app is hung.

**Comment by PhotoNomad0** [comment]
@elsylambert This is fixed in latest build `checking-extension-0.9.0-d472aac.vsix`

**Comment by elsylambert** [comment]
Looks good in the latest v0.9.0. Edits can me done multiple time and saved correctly without any delay.
